
title: [Research Technology Bioinformatics]
description: [A Series of Tufts University Research Technology Workshops]

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - lessons/
  
defaults:
  -
    scope:
      path: "tutorials"
    values:
      layout: "default"
    scope:
      path: "workshops"
    values:
      layout: "hpcForLifeSciences_July2022"
      
theme: jekyll-theme-cayman
