
title: [Research Technology Bioinformatics]
description: [A Series of Tufts University Research Technology Workshops]

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - lessons/
  
layout: default
theme: jekyll-theme-cayman
