name: Jekyll site CI from 2 branches

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Checkout the `main` branch
    - uses: actions/checkout@v3
    # Install Node.js
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
          
    # Install npm dependencies
    # (similar to npm install)
    - run: npm ci
    # Run code to build the site files inside the `main` folder
    - run: npm run build
    
    # Checkout the `main` branch
    - uses: actions/checkout@v3
      with:
        ref: main
      # Put the checked out files inside the `main/testdeploy` folder
      path: main/testdeploy
      clean: false
      # Delete the .git folder from `Research_Technology_Bioinformatics/testdeploy`
      # This turns the files into a plain folder instead of a git repository
      - run: rm -rf Research_Technology_Bioinformatics/testdeploy/.git
      # Deploy the main folder to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './main'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'


#    - name: Build the site in the jekyll/builder container
#      run: |
#        docker run \
#        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
